spring:
  application:
    name: audio-summary-server
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/audio_summary_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

